# https://alysivji.github.io/php-mysql-docker-containers.html

version: '3'

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: benjamindavies_maquo
      MYSQL_USER: benjamindavies
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
  web:
    image: php:5.5-apache
    #container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    #stdin_open: true
    #tty: true
